### ISSUE TITLE
Not able to install via Composer for Contao 4.3

### ISSUE THREAD

**Issue by fboes** [scyfel/contao-formrecipient#2]
I tried to install this plugin for Contao 4.3 using Composer. Sadly this did not work out:

```
$ composer require scyfel/contao-formrecipient
Using version ^1.2 for scyfel/contao-formrecipient
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove contao/calendar-bundle 4.3.11
    - Conclusion: don't install contao/calendar-bundle 4.3.11
```

I found this module to have a requirement for Contao <4. Is this the cause for my installation problem?

**Comment by SimonSpi** [comment]
Same here under 4.6.11. Unfortunately I didn't get any error message in my server log. It's a pitty because this plugin would be very helpful.

**Comment by christianbarkowsky** [comment]
Support from Contao 4.4
